#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define LARGEUR_FENETRE 780
#define HAUTEUR_FENETRE 380
#define TAILLE_FENETRE (LARGEUR_FENTRE*HAUTEUR_FENETRE)
#define INTERVALLE 100
#define LAPS_DE_TEMPS 3000
enum {TITRE , JOUER , QUITTER};
enum {FAUX , VRAI};


#endif // CONSTANTES_H_INCLUDED
